import AppPage from "@/app/App";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Doo Anime",
  description: "Generated by create @aecuto",
};

export default function Home() {
  return (
    <main>
      <AppPage />
    </main>
  );
}
